### ISSUE TITLE
Demo Page:  Api docs not rendering when serving with polymer

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#299]
## Description:
Serve up the component using polymer serve, note the demo page is missing all the api documentation except the headers.  This is not an issue when you gulp serve.

## Version:
data-grid tag: 1.0.3
Browsers: Chrome63, FF57, safari10 and IE11

## Screenshot:
![missing_apidocs](https://user-images.githubusercontent.com/10835611/34841109-f9c1e0a4-f6bb-11e7-80a3-25e5fe365cca.png)

**Comment by alump** [comment]
We need help with this, as if it works in one, but does not work with another, there is something strange there.

**Comment by limonte** [comment]
There are instructions how to start local development: https://github.com/vaadin/px-data-grid#local-development, please follow them.

Supporting both `gulp serve` and `polymer serve` isn't possible because of `px-demo-api-viewer`, this is the right place to report the issue: https://github.com/PredixDev/px-api-viewer/issues

**Comment by ppeyro** [comment]
Please reopen this one (I don't seem to have permission to reopen the issue). We need to make sure my dev team is ok with supporting/potentially fixing this. We have to run "polymer serve" since we need the transpiled version for testing our supported browser list.

**Comment by alump** [comment]
Fixed.
