### ISSUE TITLE
Advanced Filtering: When multiple filters, can't see all of tooltip and "See All" not working

### ISSUE THREAD

**Issue by Aileen-H** [vaadin/px-data-grid#362]
Advanced Filtering: When multiple filters, can't see all of tooltip with the filters in Demo and "See All" hyperlink text not working. NOTE: Using Chrome Browser
![screen shot 2018-01-16 at 5 30 54 pm](https://user-images.githubusercontent.com/21231643/35020915-2f662082-fae3-11e7-9849-73e340fd844a.png)

**Comment by Toshegg** [comment]
@Aileen-H, I doubt we can change cutting without any changes on your side.
This happens because we have `position: relative` on px-data-grid. We need it in order to make px-spinner centred on the grid on data loading.
One of the possible solutions can be to move popover overlay to document body as it done in https://github.com/vaadin/vaadin-overlay.

**Comment by alump** [comment]
@Aileen-H - So this can be closed?

**Comment by Aileen-H** [comment]
This can be closed.

**Comment by alump** [comment]
To be closed when that "tooltip" is removed.
