### ISSUE TITLE
Advanced Filtering: Buttons in modal appear off modal when multiple filter rows

### ISSUE THREAD

**Issue by Aileen-H** [vaadin/px-data-grid#363]
When in Modal and added multiple filters, the "Reset" "Cancel" and "Accept" buttons are appearing slightly off the modal itself. In Chrome Browser.

![screen shot 2018-01-16 at 5 33 16 pm](https://user-images.githubusercontent.com/21231643/35020999-8e945e8e-fae3-11e7-86fa-652a53a4af41.png)

**Comment by Toshegg** [comment]
@Aileen-H, this issue is related to px-modal. The only thing that I can do is to reduce modal body's content size.
![image](https://user-images.githubusercontent.com/5630034/35040674-b8d5bc0e-fb8a-11e7-909d-a25f527de0cb.png)
But it will still overflow in case of short browser's viewport:
![image](https://user-images.githubusercontent.com/5630034/35040697-d4155484-fb8a-11e7-8c51-6b66e75180f1.png)
This bug appeared after removal `overflow: auto` from px-modal. It was removed to fix the bug when modal cuts nested dropdown.

**Comment by alump** [comment]
Actually I tested this now, and it worked without any changes?

**Comment by alump** [comment]
New version of px-modal (v3.2.0) released, testing it...

**Comment by alump** [comment]
New px-modal fixed some issues, but not this.

**Comment by Aileen-H** [comment]
PRIORITY 2
