### ISSUE TITLE
Editing a date column should use datetime-picker not calendar picker

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#703]
## Description

Editing a date column triggers calendar picker. Checked with our dev team, it should use datetime picker not calendar picker.

## Version
Data-grid: V1.2.4

## Screenshot
![screen shot 2018-02-23 at 6 03 14 pm](https://user-images.githubusercontent.com/10835611/36690391-089c9cf0-1ae7-11e8-9d9e-b9422b747a1f.png)

**Comment by katemenkhaus** [comment]
It looks like the component being used is the `px-datetime-picker` because `iron-dropdown` does that weird side position stuff. It is `px-datetime-picker` that uses `iron-dropdown` not `px-calendar-picker`

Inorder to fix the cut off problem the `px-datetime-picker` should be updated and add the `hoist` property to it.

**Comment by ppeyro** [comment]
Closing this one. I think Kate validated it's the correct component.
